module.exports = {
  headerTitle: '[data-test-id="Header-Title"]',
  createAccountButton: "#createaccbtn:not([disabled])",
  createAccountBtnText: "Create Account",
  owner: "#owner",
  ownerName: "Stephan",
  secondownerName: "Patrick",
  ownerNameBlank: "",
  balance: "#balance",
  balanceBlank:"",
  balanceAmount:"9000",
  currency: "#currency",
  euro: "EURO",
  dollar: "DOLLAR",
  submitBtn: "#accountsubmit",
  submitBtnText: "Submit",
  successMessage:
    "div.notification.notification-success.notification-enter-done",
  successMessageText: "Account has been successfully created.",
  clearBtn: "#accountclear",
  clearBtnText: "Clear",
  errorMessage: "div.notification-message",
  errorMessageText: "Please fill in name.",
  errorMessageBalanceText: "Please fill in balance.",
};
