module.exports = {
  transListBtn: "#translistbtn:not([disabled])",
  transDetailsTab: '[data-test-id="Transaction-Details"]',
  infoMessage: "div.notification-message",
  messageText: "Please select date to and from for fetching records.",
  dateFrom: "#datefrom:not([disabled])",
  dateTo: "#dateto:not([disabled])",
  fromDateInput: "19122020",
  toDateInput: "31122020",
  searchBtn: "#transsearch",
  sourceNameInput: "#text-filter-column-source.owner:not([disabled])",
  destinationNameInput: "#text-filter-column-destination.owner:not([disabled])",
  bodyMessageList: "div.react-bootstrap-table > table > tbody",
  errorMessage: "div.notification-message",
  errorMessageText: "Please select both date from and date to.",
  inputDate: "12122020",
  tillDate: "18122020",
  noRecordMessageText: "No record found.",
  greaterDate: "31122020",
  lesserDate: "18122020",
  dateGreaterMessageText: "Date from cannot be greater than date to.",
};
